# Generated by Django 5.0.1 on 2025-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profile_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketattachment",
            name="ticket",
        ),
        migrations.AddField(
            model_name="faqinteraction",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
        migrations.DeleteModel(
            name="TicketAttachment",
        ),
    ]
