# Generated by Django 5.0.1 on 2025-03-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
