# Generated by Django 5.0.1 on 2025-03-12 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_servicefeature_alter_service_options_and_more"),
        ("tickets", "0002_ticket_due_date_ticket_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="contact_method",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="preferred_contact_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="services.service",
            ),
        ),
    ]
